-- Generado por Oracle SQL Developer Data Modeler 4.1.3.901
--   en:        2019-07-10 10:04:48 COT
--   sitio:      Oracle Database 11g
--   tipo:      Oracle Database 11g




CREATE TABLESPACE UPROCESOS
  --  WARNING: Tablespace has no data files defined
  LOGGING ONLINE EXTENT MANAGEMENT LOCAL AUTOALLOCATE FLASHBACK ON ;

CREATE USER UPROCESOS_USER IDENTIFIED BY ACCOUNT UNLOCK ;
  GRANT
  SELECT ANY TABLE, CREATE ANY TRIGGER, ALTER ANY SEQUENCE,
  DROP ANY SEQUENCE,
  INSERT ANY TABLE, CREATE ANY PROCEDURE,
  SELECT ANY SEQUENCE,
  UPDATE ANY TABLE,
  DROP ANY TRIGGER,
  DELETE ANY TABLE,
    CREATE ANY TABLE,
    CREATE ANY SEQUENCE,
    EXECUTE ANY PROCEDURE,
  DROP ANY TABLE, ALTER ANY TABLE TO UPROCESOS_USER
WITH ADMIN OPTION ;

CREATE TABLE UPROCESOS_USER.ADMINISTRADOR
  (
    ID         NUMBER (20) ,
    USUARIO    VARCHAR2 (15 BYTE) ,
    CONTRASEÑA VARCHAR2 (20 BYTE)
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE UPROCESOS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;


CREATE TABLE UPROCESOS_USER.CARGOS
  (
    IDCARGO  NUMBER (8) NOT NULL ,
    DESCARGO VARCHAR2 (30 CHAR)
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE UPROCESOS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX UPROCESOS_USER.CARGOS_PK ON UPROCESOS_USER.CARGOS
  (
    IDCARGO ASC
  )
  TABLESPACE UPROCESOS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
ALTER TABLE UPROCESOS_USER.CARGOS ADD CONSTRAINT CARGOS_PK PRIMARY KEY ( IDCARGO ) USING INDEX UPROCESOS_USER.CARGOS_PK ;


CREATE TABLE UPROCESOS_USER.CATEGORIAS
  (
    IDCATEGORIA     NUMBER (8) NOT NULL ,
    NOMBRECATEGORIA VARCHAR2 (15 CHAR) ,
    DESCRIPCION     VARCHAR2 (4000 CHAR)
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE UPROCESOS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX UPROCESOS_USER.CATEGORIAS_PK ON UPROCESOS_USER.CATEGORIAS
  (
    IDCATEGORIA ASC
  )
  TABLESPACE UPROCESOS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
ALTER TABLE UPROCESOS_USER.CATEGORIAS ADD CONSTRAINT CATEGORIAS_PK PRIMARY KEY ( IDCATEGORIA ) USING INDEX UPROCESOS_USER.CATEGORIAS_PK ;


CREATE TABLE UPROCESOS_USER.CLIENTES
  (
    IDCLIENTE   VARCHAR2 (5 CHAR) NOT NULL ,
    NOMCLIENTE  VARCHAR2 (40 CHAR) ,
    DIRCLIENTE  VARCHAR2 (60 CHAR) ,
    IDPAIS      CHAR (3 CHAR) NOT NULL ,
    FONOCLIENTE VARCHAR2 (25 CHAR) ,
    LINEACREDI  NUMBER (8,2)
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE UPROCESOS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX UPROCESOS_USER.CLIENTES_PK ON UPROCESOS_USER.CLIENTES
  (
    IDCLIENTE ASC
  )
  TABLESPACE UPROCESOS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
ALTER TABLE UPROCESOS_USER.CLIENTES ADD CONSTRAINT CLIENTES_PK PRIMARY KEY ( IDCLIENTE ) USING INDEX UPROCESOS_USER.CLIENTES_PK ;


CREATE TABLE UPROCESOS_USER.DISTRITOS
  (
    IDDISTRITO  NUMBER (8) NOT NULL ,
    NOMDISTRITO VARCHAR2 (50 CHAR)
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE UPROCESOS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX UPROCESOS_USER.DISTRITOS_PK ON UPROCESOS_USER.DISTRITOS
  (
    IDDISTRITO ASC
  )
  TABLESPACE UPROCESOS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
ALTER TABLE UPROCESOS_USER.DISTRITOS ADD CONSTRAINT DISTRITOS_PK PRIMARY KEY ( IDDISTRITO ) USING INDEX UPROCESOS_USER.DISTRITOS_PK ;


CREATE TABLE UPROCESOS_USER.EMPLEADOS
  (
    IDEMPLEADO   NUMBER (8) NOT NULL ,
    APEEMPLEADO  VARCHAR2 (50 CHAR) ,
    NOMEMPLEADO  VARCHAR2 (50 CHAR) ,
    FECNAC       DATE ,
    DIREEMPLEADO VARCHAR2 (60 CHAR) ,
    IDDISTRITO   NUMBER (8) NOT NULL ,
    FONOEMPLEADO VARCHAR2 (15 CHAR) ,
    IDCARGO      NUMBER (8) NOT NULL ,
    FECCONTRATA  DATE ,
    SALARY       NUMBER (8,2)
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE UPROCESOS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX UPROCESOS_USER.EMPLEADOS_PK ON UPROCESOS_USER.EMPLEADOS
  (
    IDEMPLEADO ASC
  )
  TABLESPACE UPROCESOS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
ALTER TABLE UPROCESOS_USER.EMPLEADOS ADD CONSTRAINT EMPLEADOS_PK PRIMARY KEY ( IDEMPLEADO ) USING INDEX UPROCESOS_USER.EMPLEADOS_PK ;


CREATE TABLE UPROCESOS_USER.PAISES
  (
    IDPAIS     CHAR (3 CHAR) NOT NULL ,
    NOMBREPAIS VARCHAR2 (40 CHAR)
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE UPROCESOS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX UPROCESOS_USER.PAISES_PK ON UPROCESOS_USER.PAISES
  (
    IDPAIS ASC
  )
  TABLESPACE UPROCESOS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
ALTER TABLE UPROCESOS_USER.PAISES ADD CONSTRAINT PAISES_PK PRIMARY KEY ( IDPAIS ) USING INDEX UPROCESOS_USER.PAISES_PK ;


CREATE TABLE UPROCESOS_USER.PEDIDOSCABECERA
  (
    IDPEDIDO        NUMBER (8) NOT NULL ,
    IDCLIENTE       VARCHAR2 (5 CHAR) NOT NULL ,
    IDEMPLEADO      NUMBER (8) NOT NULL ,
    FECHAPEDIDO     DATE ,
    FECHAENTREGA    DATE ,
    FECHAENVIO      DATE ,
    ENVIOPEDIDO     CHAR (1 CHAR) ,
    CANTIDADPEDIDO  NUMBER (8) ,
    DESTINATARIO    VARCHAR2 (50 CHAR) ,
    DIRDESTINATARIO VARCHAR2 (50 CHAR) ,
    CIUDESTINATARIO VARCHAR2 (50 CHAR) ,
    REFDESTINATARIO VARCHAR2 (50 CHAR) ,
    DEPDESTINATARIO VARCHAR2 (50 CHAR) ,
    PAISDESTINARAIO VARCHAR2 (50 CHAR)
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE UPROCESOS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX UPROCESOS_USER.PEDIDOSCABECERA_PK ON UPROCESOS_USER.PEDIDOSCABECERA
  (
    IDPEDIDO ASC
  )
  TABLESPACE UPROCESOS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
ALTER TABLE UPROCESOS_USER.PEDIDOSCABECERA ADD CONSTRAINT PEDIDOSCABECERA_PK PRIMARY KEY ( IDPEDIDO ) USING INDEX UPROCESOS_USER.PEDIDOSCABECERA_PK ;


CREATE TABLE UPROCESOS_USER.PEDIDOSDETALLE
  (
    IDPEDIDO     NUMBER (8) NOT NULL ,
    IDPRODUCTO   NUMBER (8) NOT NULL ,
    PRECIOUNIDAD NUMBER (8) ,
    CANTIDAD     NUMBER (5) ,
    DESCUENTO    NUMBER (8,2)
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE UPROCESOS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;


CREATE TABLE UPROCESOS_USER.PRODUCTOS
  (
    IDPRODUCTO           NUMBER (8) NOT NULL ,
    NOMPRODUCTO          VARCHAR2 (40 CHAR) ,
    IDPROVEEDOR          NUMBER (8) NOT NULL ,
    IDCATEGORIA          NUMBER (8) NOT NULL ,
    CANTXUNIDAD          VARCHAR2 (20 CHAR) ,
    PRECIOUNIDAD         NUMBER (8) ,
    UNIDADESENEXISTENCIA NUMBER (8) ,
    UNIDADESENPEDIDO     NUMBER (8)
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE UPROCESOS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX UPROCESOS_USER.PRODUCTOS_PK ON UPROCESOS_USER.PRODUCTOS
  (
    IDPRODUCTO ASC
  )
  TABLESPACE UPROCESOS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
ALTER TABLE UPROCESOS_USER.PRODUCTOS ADD CONSTRAINT PRODUCTOS_PK PRIMARY KEY ( IDPRODUCTO ) USING INDEX UPROCESOS_USER.PRODUCTOS_PK ;


CREATE TABLE UPROCESOS_USER.PROVEEDORES
  (
    IDPROVEEDOR   NUMBER (8) NOT NULL ,
    NOMPROVEEDOR  VARCHAR2 (40 CHAR) ,
    DIRPROVEEDOR  VARCHAR2 (60 CHAR) ,
    NOMCONTACTO   VARCHAR2 (80 CHAR) ,
    CARGOCONTACTO VARCHAR2 (50 CHAR) ,
    IDPAIS        CHAR (3 CHAR) NOT NULL ,
    FONOPROVEEDOR VARCHAR2 (15 CHAR)
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE UPROCESOS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;
CREATE UNIQUE INDEX UPROCESOS_USER.PROVEEDORES_PK ON UPROCESOS_USER.PROVEEDORES
  (
    IDPROVEEDOR ASC
  )
  TABLESPACE UPROCESOS PCTFREE 10 STORAGE
  (
    INITIAL 65536 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  LOGGING ;
ALTER TABLE UPROCESOS_USER.PROVEEDORES ADD CONSTRAINT PROVEEDORES_PK PRIMARY KEY ( IDPROVEEDOR ) USING INDEX UPROCESOS_USER.PROVEEDORES_PK ;


ALTER TABLE UPROCESOS_USER.CLIENTES ADD CONSTRAINT CLIENTES_PAISES_FK FOREIGN KEY ( IDPAIS ) REFERENCES UPROCESOS_USER.PAISES ( IDPAIS ) NOT DEFERRABLE ;

ALTER TABLE UPROCESOS_USER.EMPLEADOS ADD CONSTRAINT EMPLEADOS_CARGOS_FK FOREIGN KEY ( IDCARGO ) REFERENCES UPROCESOS_USER.CARGOS ( IDCARGO ) NOT DEFERRABLE ;

ALTER TABLE UPROCESOS_USER.EMPLEADOS ADD CONSTRAINT EMPLEADOS_DISTRITOS_FK FOREIGN KEY ( IDDISTRITO ) REFERENCES UPROCESOS_USER.DISTRITOS ( IDDISTRITO ) NOT DEFERRABLE ;

ALTER TABLE UPROCESOS_USER.PEDIDOSCABECERA ADD CONSTRAINT PEDIDOSCABECERA_CLIENTES_FK FOREIGN KEY ( IDCLIENTE ) REFERENCES UPROCESOS_USER.CLIENTES ( IDCLIENTE ) NOT DEFERRABLE ;

ALTER TABLE UPROCESOS_USER.PEDIDOSCABECERA ADD CONSTRAINT PEDIDOSCABECERA_EMPLEADOS_FK FOREIGN KEY ( IDEMPLEADO ) REFERENCES UPROCESOS_USER.EMPLEADOS ( IDEMPLEADO ) NOT DEFERRABLE ;

ALTER TABLE UPROCESOS_USER.PEDIDOSDETALLE ADD CONSTRAINT PEDIDOSDETALLE_PRODUCTOS_FK FOREIGN KEY ( IDPRODUCTO ) REFERENCES UPROCESOS_USER.PRODUCTOS ( IDPRODUCTO ) NOT DEFERRABLE ;

ALTER TABLE UPROCESOS_USER.PRODUCTOS ADD CONSTRAINT PRODUCTOS_CATEGORIAS_FK FOREIGN KEY ( IDCATEGORIA ) REFERENCES UPROCESOS_USER.CATEGORIAS ( IDCATEGORIA ) NOT DEFERRABLE ;

ALTER TABLE UPROCESOS_USER.PRODUCTOS ADD CONSTRAINT PRODUCTOS_PROVEEDORES_FK FOREIGN KEY ( IDPROVEEDOR ) REFERENCES UPROCESOS_USER.PROVEEDORES ( IDPROVEEDOR ) NOT DEFERRABLE ;

ALTER TABLE UPROCESOS_USER.PROVEEDORES ADD CONSTRAINT PROVEEDORES_PAISES_FK FOREIGN KEY ( IDPAIS ) REFERENCES UPROCESOS_USER.PAISES ( IDPAIS ) NOT DEFERRABLE ;

CREATE OR REPLACE TRIGGER UPROCESOS_USER.AUTO_ID_ADMIN 
    BEFORE INSERT ON UPROCESOS_USER.ADMINISTRADOR 
    FOR EACH ROW 
BEGIN
  SELECT ID_ADMI.NEXTVAL INTO :NEW.ID FROM DUAL;
END; 
/




-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             9
-- ALTER TABLE                             18
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           1
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        1
-- CREATE USER                              1
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 1
